# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  topschoolapi:
    image: topschoolapi
    build:
      context: .
      dockerfile: TopSchool.API/Dockerfile
    ports:
      - 5067:5067
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
